name: GitHub Actions Practice

run-name: ${{ github.actor }} is testing out GitHub Actions

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "Name of your branch - ${{ github.ref }}"
      - run: echo "Name of respository - ${{ github.repository }}"
      - name: Checkout repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} has been cloned to the runner."
      - run: echo "💻 The workflow is now ready to test the code on the runner."
      - name: "List files in the repository"
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
